import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { RoleProvider } from "@/components/role/RoleProvider";
import { Header } from "@/components/Header";
import { TransparencyLog } from "@/components/transparency/TransparencyLog";
import Sidebar from "@/components/Sidebar";
import { PageTransition } from "@/components/animate/PageTransition";

const inter = Inter({ subsets: ["latin"] });
const plex = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Sentient University",
  description: "Generated by Inova AI Solutions",
  icons: { icon: "/logo.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${plex.className} min-h-screen flex flex-col`}>
        <RoleProvider>
          <Header />
          <div className="flex-1 lg:flex">
            <Sidebar />
            <main className="flex-1">
              <PageTransition>{children}</PageTransition>
            </main>
          </div>
          <TransparencyLog />
        </RoleProvider>
      </body>
    </html>
  );
}
