import type { Metadata, Viewport } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { AccountMenu } from "@/components/nav/AccountMenu";
import { RoleProvider } from "@/components/role/RoleProvider";
import Sidebar from "@/components/Sidebar";
import { PageTransition } from "@/components/animate/PageTransition";
import { CommandMenu } from "@/components/CommandMenu";
import { ToastProvider } from "@/components/ui/Toast";
import { DensityProvider } from "@/components/prefs/DensityProvider";
import { NotificationProvider } from "@/components/notifications/NotificationProvider";
import { AssistantDrawer } from "@/components/assistant/AssistantDrawer";
import { MessageCenterProvider } from "@/context/MessageCenterContext";
import { NewsCenterProvider } from "@/context/NewsCenterContext";
import TopbarActions from "@/components/topbar/TopbarActions";
import MessageCenterSheet from "@/components/topbar/MessageCenterSheet";
import LatestNewsButton from "@/components/topbar/LatestNewsButton";
import NewsCenterSheet from "@/components/topbar/NewsCenterSheet";

const inter = Inter({ subsets: ["latin"] });
const plex = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Sentient University",
  description: "Generated by Inova AI Solutions",
  icons: { icon: "/logo.png" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${plex.className} min-h-screen flex flex-col`}>
        <ToastProvider>
        <DensityProvider>
        <NotificationProvider>
        <MessageCenterProvider>
        <NewsCenterProvider>
        <RoleProvider>
          <a href="#main" className="sr-only focus:not-sr-only fixed left-2 top-2 z-50 rounded-control bg-surface px-3 py-2 text-sm text-ink shadow-elevation-sm outline outline-2 outline-primary outline-offset-2">Skip to content</a>
          <div className="flex-1 lg:flex">
            <Sidebar />
            <main id="main" className="relative flex-1">
              <div className="fixed right-4 top-2 z-40">
                <div className="flex items-center gap-2 rounded-full border border-line/60 bg-white px-2 py-1 shadow-[0_12px_28px_rgba(0,0,0,0.18)]">
                  <TopbarActions />
                  <LatestNewsButton />
                  <AccountMenu />
                </div>
              </div>
              <PageTransition>{children}</PageTransition>
            </main>
          </div>
          <CommandMenu />
          <AssistantDrawer />
          <MessageCenterSheet />
          <NewsCenterSheet />
        </RoleProvider>
        </NewsCenterProvider>
        </MessageCenterProvider>
        </NotificationProvider>
        </DensityProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
